import Head from "next/head";
import Image from "next/image";
import { capitalize } from "#/utils";
import Button from "~/core/Button";
import Layout from "~/layout/Layout";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Layout>
				<main id="main-content"></main>
			</Layout>
			<style jsx>
				{`
					#hero {
						height: calc(100vh - 80px);
					}

					.gradient-text {
						background: linear-gradient(
							95.01deg,
							#ef8cff -2.22%,
							rgba(59, 93, 215, 0.630208) 38.73%,
							rgba(61, 186, 89, 0.79) 73.42%,
							rgba(41, 49, 42, 0.79) 106.98%
						);
						-webkit-background-clip: text;
						-webkit-text-fill-color: transparent;
						background-clip: text;
						text-fill-color: transparent;
					}

					.background-gradient {
						background: linear-gradient(
							90deg,
							#12c2e9 0%,
							#c471ed 45.31%,
							#f64f59 100%
						);
					}
				`}
			</style>
		</>
	);
}
